sudo: required
services:
- docker
language: node_js
node_js:
- '5'
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: Dc6Ro2TKkHyRGKVgQqHna2PWy1jNmfjGg68JpfxSvufUMKqVJLKdLtPspBhqN/TxcEisAvRFZ0tccpKbfUdLVIWupyfJ1bslMCtB9Txtac7ClzkDKIpXn6/6L8hSQpEuv1h911w1MQ8xRtUpt7dKRStnxnux9QD24+9cvXUbGuRpNCfF5JuK7rxrpUO5h297fjK2DtsvJQAibNJhyIp7j5UVrxP8UAWbxKZhg8kjg5AzNAIRh5KBVZB4X6+taz4R3u6+hPqlzRIUby8Z1Q8Mv4K1taz7OwF1RGfqmwqB9krPJ9t4dh9fevQmy0BNpK2z0l6ci5tyNEkHzjaT9mR3OVFguyILCJE2OTxFCcWdhmbbe+OopLEgHaIflRk0h7K6yvxLOkH62LG8gTSL+y4J8HYDtuL92SOUJiFgITG4To/DP/W7le7nH4IZuET3wUiTsWTNxabOhC5Eep1KojN9ATaB8yCtCv91RIClro61Hqy62OaOYHbF80hgLeTgu/QQzgC3dLPEmyiIRBYtnK+AJpIRp4aQ4Hu82o8uYxDXEzOvgNk7KeX7EbvJLa73LMPkjqJy4LFuxNwUadp2THUyjnlZL8+sAh0HC7Jli/LWBg1ThkAUhx1JDL3m7XbUX5f/9LhfPykQtvocmHr51z2J1ULIM2tkf4NlYBChCZGIhww=
  - secure: jGaloInQybJ86pjTcim+zJhMqbatcKXr7VbzJyzJSugRGpA08S9CwmK3XuQG943v8QWLJIkquivIsacabCQV9MaOKZydBCEXeRbYgCd2QvXmGjLI/TKyxy7KW30PN9+BDg1Q1U/fS6sX6PgYrB97mAkutgh5zXUUfJamvfX3hym1SlQGr8EcktvC8RdUgTo9r9SJHuU27m+jQvVoTkdJRIT+ygWdD0ikLr53X+5HfMJwxYgeKe9K6eohLrmgunD586degwufIEJcuMToklKJ0UZoANEsUtYr9TkcssZNU6+1l2Ydqwhq1DjCd8VP+ysTMdE6kNTc7h/zrqSjuVgV007BYwzcz2dl/2BpV5otrx5t2+HOxVo29P0AaWBtq5Td0kr1UUwwWa1kkXRyDZVL+VQ+60E+75xRB22sPl5PLirCR85TTxju1zIBe0yxtWGp6u4HHqkQ+h1zRme1NCfFoBEKWI6rr6SrlnlNky+M8fEoQ3XqSOb7OFBUHWaRWW2PG/Y842jxYLH52qjudxgDTbCwTcMk94Rogvvg6itMDHnmTMCe+SQxlO/pN8bzVZbhM/JyygHW5SKzWMqE9OFrVpSIDcpSMMNmDVlFdzHIPOcWr1xgfNQK2VJC4bWKeXVP+JXGLLyzRgnmkiffZJeK9Onn1xBkc3kuIpYOQlc4JFk=
script:
- docker build -t ddns-travis .
- docker run -d -P --name ddns-travis ddns-travis
- docker exec ddns-travis grunt test
- docker exec ddns-travis npm install -g codeclimate-test-reporter
- docker exec ddns-travis grunt coverage
- docker exec -it ddns-travis sh -c 'codeclimate-test-reporter < /ddns/coverage/lcov.info'
after_success:
- export REPO=Samisdat/ddns
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH;
  fi`
- echo $REPO
- echo $COMMIT
- echo $TAG
- curl -H "Content-Type:application/json" --data '{"build":true}' -X POST https://registry.hub.docker.com/u/samisdat/ddns/trigger/$DOCKER_TOKEN/
