#!/bin/bash
#
# 

create_key(){
	mkdir -p /ddns/key
	rm -f /ddns/key/Kddns_update*
	
	local cms=($(dnssec-keygen -K key/ -a HMAC-MD5 -b 128 -r /dev/urandom -n USER DDNS_UPDATE))
	KEY=$(cat /ddns/key/Kddns_update*.private | grep Key | cut -d " " -f 2)

	echo "key \"DDNS_UPDATE\" {
		algorithm hmac-md5;
		secret \"$KEY\";
	};" >> /etc/bind/named.conf.local

}

create_zone(){
	local NAMESERVER=$1
	local DYNAMIC_DOMAIN=$2

	DB="db.$DYNAMIC_DOMAIN"
	rm -f "/etc/bind/$DB"
	touch "/etc/bind/$DB"

echo "TDL	30
@	IN	SOA	$NAMESERVER. root.localhost. (
			      3		; Serial
			 604800		; Refresh
			  86400		; Retry
			2419200		; Expire
			  86400 )	; Negative Cache TTL
;
@		IN	NS	$NAMESERVER.
@		IN	A	127.0.0.1
*		IN	CNAME 	$DYNAMIC_DOMAIN.	
" > "/etc/bind/$DB"
	echo "zone "$DYNAMIC_DOMAIN" {
		type master;
		file "/etc/bind/$db";
		allow-update { key "DDNS_UPDATE"; };
	};" >> /etc/bind/named.conf.local
	
}

read_config(){
	local  CONFIGFILE="$1"
	#@TODO some validation
	NAMESERVER=$(cat $CONFIGFILE | grep NAMESERVER | cut -d " " -f 2)
	DYNAMIC_DOMAIN=$(cat $CONFIGFILE | grep DYNAMIC_DOMAIN | cut -d " " -f 2)
	local my_list=("$NAMESERVER" "$DYNAMIC_DOMAIN")  
	echo "${my_list[@]}" 
}

read_configs(){	

	for filename in /ddns/config/*; do
    		read_config $filename
		local result=( $(read_config $filename))

		( $(create_zone ${result[0]} ${result[1]})) 
	done

}

rm -f /etc/bind/named.conf.local

touch /etc/bind/named.conf.local

echo "// generated by samisdat/ddns" > /etc/bind/named.conf.local


create_key
read_configs