#!/bin/bash
#
# 

create_key(){
	mkdir -p /ddns/key
	rm -f /ddns/key/Kddns_update*
	
	local silent=( $(dnssec-keygen -K key/ -a HMAC-MD5 -b 128 -r /dev/urandom -n USER DDNS_UPDATE) )
	KEY=$(cat /ddns/key/Kddns_update*.private | grep Key | cut -d " " -f 2)

	sed "s@DNSSEC_KEY@$KEY@g" /ddns/templates/key >> /etc/bind/named.conf.local
}

create_zone(){
	local NAMESERVER=$1
	local DYNAMIC_DOMAIN=$2

	rm -f "/etc/bind/db.$DYNAMIC_DOMAIN"
	touch "/etc/bind/db.$DYNAMIC_DOMAIN"
	chown bind:bind "/etc/bind/db.$DYNAMIC_DOMAIN"


	sed "s@NAMESERVER@$NAMESERVER@g;s@DYNAMIC_DOMAIN@$DYNAMIC_DOMAIN@g" /ddns/templates/db >> "/etc/bind/db.$DYNAMIC_DOMAIN"

	sed "s@DYNAMIC_DOMAIN@$DYNAMIC_DOMAIN@g" /ddns/templates/zone  >> /etc/bind/named.conf.local
	
}

read_config(){
	local  CONFIGFILE="$1"
	#@TODO some validation
	NAMESERVER=$(cat $CONFIGFILE | grep NAMESERVER | cut -d " " -f 2)
	DYNAMIC_DOMAIN=$(cat $CONFIGFILE | grep DYNAMIC_DOMAIN | cut -d " " -f 2)
	local my_list=("$NAMESERVER" "$DYNAMIC_DOMAIN")  
	echo "${my_list[@]}" 
}

read_configs(){	

	for filename in /ddns/config/*; do
    		read_config $filename
		local result=( $(read_config $filename))

		( $(create_zone ${result[0]} ${result[1]})) 
	done

}

rm -f /etc/bind/named.conf.local

touch /etc/bind/named.conf.local
chown bind:bind /etc/bind/named.conf.local

echo "// generated by samisdat/ddns" > /etc/bind/named.conf.local


create_key
read_configs

#service bind9 restart

