#!/bin/bash
#echo "server NAMESERVER"
echo "server localhost"
echo "zone DYNAMIC_DOMAIN"
echo "update delete DYNAMIC_DOMAIN. A"
echo "update add DYNAMIC_DOMAIN 30 IN A $(ifconfig | grep inet | grep -v "inet6" | grep -v "127.0.0.1" | cut -d " " -f 2 | head -n 1)"
echo "show"
echo "send"

